project:
  type: website

website:
  title: "NY"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: plots/ELAcountyreport-2025.qmd
        text: ELA-County

format:
  html:
    theme: [minty, custom.scss]
    toc: true



