project:
  type: website
  resources:
    - CNAME

website:
  title: "NY"
  site-url: "https://data.openschooldata.com/"
  open-graph: true
  sidebar:
    style: floating
    logo: images/OSD-favicon.png
    search: true
    contents:
      - href: index.qmd
        text: Reports / Plots
      - href: ELAcountyreport-2025.qmd
        text: ELA Proficiency - 2025
        icon: file-bar-graph
        

format:
  html:
    page-layout: full
    theme: [minty, custom.scss]
    toc: false



