project:
  type: website
  resources:
    - CNAME

website:
  title: "Open School Data (NY)"
  site-url: "https://www.openschooldata.com/"
  open-graph: true
  sidebar: false

format:
  html:
    page-layout: full
    theme: 
      - minty
      - custom.scss
    toc: false



